version: "3.7"
networks:
  smacktalkapp:
    driver: bridge

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - APP_ENV=${APP_ENV}
    volumes:
      - /home/thebogie/work/stgdata:/data/db
    ports:
      - 27017:27017
    command: mongod

    networks:
      - smacktalkapp

  stgserver:
    #command: --security-opt=seccomp:unconfined
    container_name: stgserver
    environment:
      - APP_ENV=${APP_ENV}
    build:
      context: ./server

    ports:
      - 5000:5000
    depends_on:
      - mongodb

    networks:
      - smacktalkapp

  #stgapp:
  #  container_name: stgapp
  #  environment:
  #    - APP_ENV=${APP_ENV}
  #  build:
  #    context: ./frontend

  #  ports:
  #    - 3000:3000
  #    - 10000:10000

  #  networks:
  #    - smacktalkapp
  #frontend:
  #  build:
  #    context: ./frontend
  #    args:
  #      app_env: ${APP_ENV}
  #  volumes:
  #    - ./frontend/src:/frontend/src
  #    - '/frontend/node_modules'
  #  ports:
  #    - "3000:3000"
  #    - "9229:9229"
  #apache:
  #  image: "bitnami/apache:latest"
  #ports:
  #  - "80:5000"
  #  - "443:8443"
  # container_name: apache
  # networks:
  #  - app-tier
  # ports:
  #  - 80:8080
  #  - 443:8443
  # volumes:
  #  - /home/thebogie/work/smacktalkgaming/apache/my_vhost.conf:/vhosts/my_vhost.conf:ro
  #- ./certs:/certs
  # - /home/thebogie/work/smacktalkgaming/apache/mitchgottlieb.com:/app
  #- /home/thebogie/work/smacktalkgaming/apache/smacktalkgaming.com:/app/smacktalkgaming.com
 # nginx:
 #   container_name: nginx
 #   build:
 #     context: ./nginx
 #   environment:
 #     - APP_ENV=${APP_ENV}
 #   volumes:
 #     - /home/thebogie/work/smacktalkgaming/nginx/error.log:/etc/nginx/error_log.log
 #     - /home/thebogie/work/smacktalkgaming/nginx/cache/:/etc/nginx/cache
 #     - /etc/letsencrypt/:/etc/letsencrypt/
 #     - /home/thebogie/work/smacktalkgaming/nginx/srv/mitchgottlieb.com:/www/mitchgottlieb.com
 #     - /home/thebogie/work/smacktalkgaming/nginx/srv/smacktalkgaming.com:/www/smacktalkgaming.com

  #  networks:
  #    - app-tier
  #  ports:
  #    - 80:80
   #   - 443:443
